### ISSUE TITLE
doesn't install properly using jspm for systemjs

### ISSUE THREAD

**Issue by dkent600** [Vheissu/Aurelia-Configuration#53]
installing as `jspm install aurelia-configuration`.  systemjs is the module loader.

when running in chrome, the following error message occurs:

`Unhandled rejection Error: (SystemJS) Error: XHR error (404 Not Found) loading [...]/jspm_packages/github/vheissu/aurelia-configuration@1.0.9.js`

Which makes sense, as that file is indeed missing.  Every other aurelia module installation does include a corresponding file.  So it appears that this type of file is required by commonjs (I'm a newbie on this stuff so can't speculate any further.)

At any rate, the aurelia-configuration modeul will not load.

**Comment by ycharron-cstj** [comment]
I get the same error, when I installed the plugin this morning.

**Comment by M4tini** [comment]
This is fixed and a pull request is submitted. We just have to wait for @Vheissu to merge it when releasing 1.10.

**Comment by ts3li0t** [comment]
I can confirm the src latest and greatest is working with SystemJS. I did need to add the following aurelia-configuration@1.0.9.js in jspm_modules/github/vheissu, but I suspect that will be resolved as @M4tini indicates above:

define(["github:vheissu/aurelia-configuration@1.0.9/index"], function(main) {
  return main;
});

**Comment by Vheissu** [comment]
Fixed version will be released shortly.

**Comment by Vheissu** [comment]
1.0.11 fixes this.

**Comment by dkent600** [comment]
jspm install auralia-configuration doesn't work at all, says "Repo jspm:auralia-configuration not found. Perhaps try jspm install npm:auralia-configuration", which doesn't work either.

**Comment by M4tini** [comment]
@dkent600 try aurelia instead of auralia ;)

**Comment by dkent600** [comment]
Hah!  Indeed it works with an 'e'.  Typings still don't tho (another issue).  Thanks for the heads up.

**Comment by ts3li0t** [comment]
thanks, @Vheissu!
